version: '3.2'

services:
    mariadb:
        image: mariadb:10.4.6
        environment:
            - MYSQL_HOST
            - MYSQL_ROOT_PASSWORD
            - MYSQL_DATABASE
            - MYSQL_USER
            - MYSQL_PASSWORD
        volumes:
            - mariadb:/var/lib/mysql

    nginx:
        image: nginx:1.17.2-alpine
        expose:
            - 443
        depends_on:
            - php
        environment:
            DOMAIN_NAME: default:${DOMAIN_DEFAULT}
        volumes:
            - ./docker/nginx/certs:/etc/nginx/certs:ro
            - ./docker/nginx/vhost.conf:/etc/nginx/conf.d/default.conf:ro
            - ./public/:/srv/public/:ro

    php:
        build:
            context: ./docker/php
        working_dir: /srv
        depends_on:
            - mariadb
        environment:
            XDEBUG: ${XDEBUG}
            PHP_IDE_CONFIG: serverName=${XDEBUG_SERVER_NAME}
            XDEBUG_CONFIG: remote_host=${LOCAL_IP} remote_port=${XDEBUG_PORT} idekey=${XDEBUG_IDEKEY}
        volumes:
            - ~/.composer:/home/.composer
            - ./docker/config/bashrc:/home/.bashrc
            - ./docker/config/bash_aliases:/home/.bash_aliases
            - ./docker/data/history:/home/.bash_history
            - ./:/srv/

volumes:
    mariadb: ~
