App\Entity\Address:
  attributes:
    route_prefix: "/renarou"
    security: 'is_granted("ROLE_USER")'
  collectionOperations:
    get: ~
    post: ~
  itemOperations:
    get:
      security: 'is_granted("ROLE_USER") and object.user.getId() == user.getId()'
    patch:
      security: 'is_granted("ROLE_USER") and object.user.getId() == user.getId()'
    delete:
      security: 'is_granted("ROLE_ADMIN")'
