App\Entity\User:
  attributes:
    formats:
      json: ['application/merge-patch+json']
  collectionOperations:
    get:
      security: 'is_granted("ROLE_ADMIN")'
      normalization_context:
        groups: ['get']
    create_user:
      method: 'POST'
      path: '/create_user'
      controller: 'App\Controller\CreateUser'
      normalization_context:
        groups: ['get']
  itemOperations:
    get:
      security: 'is_granted("ROLE_ADMIN") or object.getId() == user.getId()'
      normalization_context:
        groups: ['get']
    update_user:
      security: 'is_granted("ROLE_USER") and object.getId() == user.getId()'
      method: 'PATCH'
      path: '/users/{id}'
      controller: 'App\Controller\UpdateUser'
      normalization_context:
        groups: ['get']

